### ISSUE TITLE
could image_folder_dataset return targets as tensors

### ISSUE THREAD

**Issue by skeydan** [mlverse/torchvision#12]
Could we make it so that `image_folder_dataset` does not need this `target_transform`?
(It's not necessarily evident to the user that this is required, and could be difficult to find out when translating from Python.)

```
target_transform = function(x) {
  x <- torch_tensor(x, dtype = torch_long())
  x$squeeze(1)
}
```

**Comment by dfalbel** [comment]
Should be fixed with https://github.com/mlverse/torch/pull/269

**Comment by skeydan** [comment]
thanks!
