### ISSUE TITLE
Unable to download package

### ISSUE THREAD

**Issue by tonyelhabr** [mlverse/torchvision#18]
I've downloaded torch successfully, but I'm not able to download torchvision.

```r
remotes::install_github('mlverse/torchvision')
```

```
Downloading GitHub repo mlverse/torchvision@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/mlverse/torchvision/tarball/master'
```

I've checked that my `{remotes}` package is fine by downloading a different package with it.

**Comment by dfalbel** [comment]
Ah maybe that's because we use 'main' instead of commonly used 'master' branch. Can you try using:

```
remotes::install_github('mlverse/torchvision@main')
```

Or update remotes.

**Comment by tonyelhabr** [comment]
Yes, that works. Thank you.

**Comment by dfalbel** [comment]
Glad it worked! Thanks!
