### ISSUE TITLE
Failed to Install

### ISSUE THREAD

**Issue by drande09** [mlverse/torchvision#19]
When I run devtools::install_github or remotes::install_github, I get a failed to install error: 

devtools::install_github("mlverse/torchvision")

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`mlverse`) and repo name (`torchvision`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by dfalbel** [comment]
Hi! I think this is a duplicate of #18 the solution is in [this specific comment](you can install with: https://github.com/mlverse/torchvision/issues/18#issuecomment-701516008)

**Comment by drande09** [comment]
thanks!
