### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by meystingray** [mlverse/torchvision#21]
Both of these are failing within RStudio:

`devtools::install_github("mlverse/torchvision"), 
remotes::install_github("mlverse/torchvision")`

Giving the error message: 
`> remotes::install_github("mlverse/torchvision")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`mlverse`) and repo name (`torchvision`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.`

**Comment by dfalbel** [comment]
Hi @meystingray !

You can find the solution here: https://github.com/mlverse/torchvision/issues/18#issuecomment-701516008

**Comment by meystingray** [comment]
@dfalbel  Yes that works...thanks!

**Comment by dfalbel** [comment]
Ok! Glad it worked!!
