### ISSUE TITLE
problem in rotate_impl

### ISSUE THREAD

**Issue by skeydan** [mlverse/torchvision#29]
The matrix returned from `get_inverse_affine_matrix` is 1-dimensional, and so cannot be reshaped like this:

```
> img <- torch_randint(0, 256, 16)$view(c(4,4))
> center_f <- c(0.0, 0.0)
> angle <- 180
> matrix <- get_inverse_affine_matrix(center_f, -angle, c(0.0, 0.0), 1.0, c(0.0, 0.0))
> theta <- torch::torch_tensor(matrix)$reshape(1, 2, 3)
Error in o(x, x$private, ...) : unused arguments (2, 3)
> matrix
[1] -1.000000e+00 -1.224647e-16  0.000000e+00  1.224647e-16
[5] -1.000000e+00  0.000000e+00
```

Would have liked to create a PR but this gets rather complex - in Python the value returned from `_get_inverse_affine_matrix` is a list as well, but it seems that in further processing we're doing something differently from Python:

```
# https://github.com/pytorch/pytorch/blob/74b65c32be68b15dc7c9e8bb62459efbfbde33d8/aten/src/ATen/native/
# AffineGridGenerator.cpp#L18
# Difference with AffineGridGenerator is that:
# 1) we normalize grid values after applying theta
# 2) we can normalize by other image size, such that it covers "extend" option like in PIL.Image.rotate
gen_affine_grid <- function(theta, w, h, ow, oh) {

```

**Comment by dfalbel** [comment]
#29 will probably fix. Can you send the code you are running so I can add a regression test?

**Comment by skeydan** [comment]
Not yet fixed, but I wanted to continue on that, which ended up in a separate PR building on yours because I wasn't able to push to your branch - hope that's ok ... https://github.com/mlverse/torchvision/pull/31 ... unfortunately that doesn't fix it yet (((but personally I'm happy to see that I'm not the only one who gets confused over whether to use `c(x, y, z)` or just `(x, y, z)` Python-style...

Here is some test code - 2 versions, on different levels of abstraction:

```
# low-level
img <- torch_randint(0, 256, 16)$view(c(4,4))
center_f <- c(0.0, 0.0)
angle <- 180
matrix <- get_inverse_affine_matrix(center_f, -angle, c(0.0, 0.0), 1.0, c(0.0, 0.0))
rotate_impl(img, matrix=matrix, resample=0, expand = FALSE, fill = NULL)

# high-level
img <- torch_randint(0, 256, 16)$view(c(4,4))
angle <- 180
transform_rotate(img, angle)

```

**Comment by dfalbel** [comment]
I am not sure it's supposed to work with 2d tensors. Images in torch are represented by 3d tensors in the CHW. I added tests to your PR.

**Comment by skeydan** [comment]
yeah me neither ... but I checked, it failed with 3d as well ...  - althpugh it's true, the error is different ...

**Comment by dfalbel** [comment]
OK, should e working with the last fix I pushed to your PR now

**Comment by skeydan** [comment]
it does, - awesome!
