### ISSUE TITLE
transform_to_tensor() from 'image-magick' return 3 channels instead of 1

### ISSUE THREAD

**Issue by Athospd** [mlverse/torchvision#34]
Dims of input image-magick differs from transform_to_tensor()'s output: It should has 1 channel (grayscale), got 3 channels. Is it expected?

``` r
img <- magick::image_blank(2, 3)
img_in_gray_scale <- magick::image_quantize(img, colorspace = "Gray")

img_in_gray_scale[[1]]
#> 1 channel 2x3 bitmap array: 'bitmap' raw [1, 1:2, 1:3] ff ff ff ff ...
torchvision::transform_to_tensor(img_in_gray_scale)
#> torch_tensor
#> (1,.,.) = 
#>   1  1
#>   1  1
#>   1  1
#> 
#> (2,.,.) = 
#>   1  1
#>   1  1
#>   1  1
#> 
#> (3,.,.) = 
#>   1  1
#>   1  1
#>   1  1
#> [ CPUFloatType{3,3,2} ]
```

<sup>Created on 2020-12-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dfalbel** [comment]
This is expected! Sometimes you have some grayscale images in the middle of a dataset and it's very hard to debug when `transform_to_tensor` can return tensors of different sizes. I would transform to grayscale with:

```
img %>% transform_to_tensor() %>% transform_rgb_to_grayscale()()
```

**Comment by Athospd** [comment]
great! thanks. closing this issue, then.
