### ISSUE TITLE
confusion about the label of mnist dataset

### ISSUE THREAD

**Issue by yuxiaokang-source** [mlverse/torchvision#37]
```
library(torch) 
library(torchvision) 
# Datasets and loaders ---------------------------------------------------- 
dir <- "~/yxk/data/mnist/" #caching directory 

train_ds <- mnist_dataset( 
 dir, 
 download = FALSE, 
 transform = transform_to_tensor 
 ) 

test_ds <- mnist_dataset( 
 dir, 
 train = FALSE, download=FALSE,
 transform = transform_to_tensor 
 ) 

train_dl <- dataloader(train_ds, batch_size = 512, shuffle = TRUE) 

for(b in enumerate(train_dl)){
    print(b[[2]])
    break
}
```
the result is below:
![image](https://user-images.githubusercontent.com/59059267/105118151-cf41e400-5b08-11eb-98b8-dfb5ea7df87e.png)
as you can see from the result, the label of the digits is from 1 to 10, not 0 to 9. Anyway, I think the label should be 0 to 9, It
make sense.

**Comment by dfalbel** [comment]
Actually this is intentional. In torch for R we start all indexes from 1 (as opposed to zero in python). If you want to get the class name, you can always do something like:

```
library(torchvision)

root <- tempfile()
d <- mnist_dataset(root = root, download = TRUE)
d$classes[d[1]$y]
```
