### ISSUE TITLE
"Corrupt file!" When downloading cifar10 and cifar100

### ISSUE THREAD

**Issue by whipson** [mlverse/torchvision#51]
Trying to get cifar10 data using the helper `cifar10_dataset` and it fails with "Corrupt file!". Not sure how to proceed from here.

```
library(dplyr)
library(torch)
library(torchvision)

transformed_cifar10 <- cifar10_dataset(".", 
                                       train = TRUE, 
                                       download = TRUE)
```
Output:
```
trying URL 'https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz'
Content type 'application/x-gzip' length 170052171 bytes (162.2 MB)
======================================downloaded 124.5 MB

Error: Corrupt file!
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by dfalbel** [comment]
It looks like the file md5 hash has changed on the server: https://github.com/mlverse/torchvision/blob/main/R/dataset-cifar.R#L22

And for security reasons we don't try to do anything else with it. We will need to update it and do a patch release of torchvision.
