### ISSUE TITLE
Bug in tiny imagenet

### ISSUE THREAD

**Issue by sebffischer** [mlverse/torchvision#94]
``` r
dir = tempfile()

torchvision::tiny_imagenet_dataset(dir, download = TRUE)
#> Downloding tiny imagenet dataset!
#> Download complete. Now unzipping.
#> Warning in file(file, "rt"): cannot open file
#> '/tmp/RtmpAv0Phl/file278fa3ce9e4ea/tiny-imagenet-200/val/val_annotations.txt':
#> No such file or directory
#> Error in file(file, "rt"): cannot open the connection
```

<sup>Created on 2023-07-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dfalbel** [comment]
I suspect this is caused by https://github.com/r-lib/zip/issues/99
Can you try installing the dev version to see if the problem is fixed?

**Comment by sebffischer** [comment]
Thanks, this was indeed the problem. Installing the dev version of `zip` fixed the issue.

**Comment by dfalbel** [comment]
I'll bump the required zip version once this dev zip version is on CRAN. 
We could use a different unzip library in the meantime as a workaround, but not sure if it's worth the effort.

**Comment by sebffischer** [comment]
Maybe it's worth to add some tests to check that the datasets can be downloaded though.
